version: "3.8"

services:
  go-tpl-service:
    build:
      context: ./
      dockerfile: ./go-tpl-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./internal/config:/app/internal/config # Mount the config directory
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: "postgres:14.0"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
